### ISSUE TITLE
list deps Crash

### ISSUE THREAD

**Issue by Kolano** [hatching/vmcloak#154]
The command...
```
vmcloak list deps
```
...lists things up until Chrome, then crashes out...
```
chrome
  * 46.0.2490.80 None a0ade494dda8911eeb68c9294c2dd0e3229d8f02
    latest       None
Traceback (most recent call last):
  File "/usr/local/bin/vmcloak", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vmcloak/main.py", line 695, in _list_deps
    list_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/vmcloak/main.py", line 682, in list_dependencies
    print exe.get("target"), exe["sha1"]
KeyError: 'sha1'
```

**Comment by Kolano** [comment]
This seems to be related to https://github.com/hatching/vmcloak/pull/140

**Comment by samwakel** [comment]
This issue is present in the pip version of VMCloak, however pull request #151 has fixed it for me. Try installing the GitHub version and see if that fixes your issue.
