### ISSUE TITLE
vmcloak.exceptions.CommandError

### ISSUE THREAD

**Issue by andrie05** [hatching/vmcloak#181]
cuckoo@kali:~$ vmcloak init  --win7x64 win7x64base --cpus 2 --ramsize 2048 -v -d
DEBUG:vmcloak.abstract:Executing genisoimage: /usr/bin/genisoimage -quiet -b boot.img -o /home/cuckoo/.vmcloak/iso/win7x64base.iso -no-emul-boot -iso-level 2 -udf -J -l -D -N -joliet-long -relaxed-filenames -allow-limited-size /home/cuckoo/.vmcloak/iso/tmpEDNk49
DEBUG:vmcloak.vm:Running command: ['/usr/bin/VBoxManage', 'createvm', '--register', '--name', 'win7x64base', '--basefolder', '/home/cuckoo/.vmcloak/vms']
VBoxManage: error: Machine settings file '/home/cuckoo/.vmcloak/vms/win7x64base/win7x64base.vbox' already exists
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "CreateMachine(bstrSettingsFile.raw(), bstrName.raw(), ComSafeArrayAsInParam(groups), bstrOsTypeId.raw(), createFlags.raw(), machine.asOutParam())" at line 274 of file VBoxManageMisc.cpp
ERROR:vmcloak.vm:[-] Error running command: Command '['/usr/bin/VBoxManage', 'createvm', '--register', '--name', 'win7x64base', '--basefolder', '/home/cuckoo/.vmcloak/vms']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/vmcloak", line 11, in <module>
    load_entry_point('VMCloak', 'console_scripts', 'vmcloak')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/cuckoo/.local/lib/python2.7/site-packages/vmcloak/main.py", line 258, in init
    m.create_vm()
  File "/home/cuckoo/.local/lib/python2.7/site-packages/vmcloak/vm.py", line 75, in create_vm
    basefolder=vms_path, register=True)
  File "/home/cuckoo/.local/lib/python2.7/site-packages/vmcloak/vm.py", line 41, in _call
    raise CommandError
vmcloak.exceptions.CommandError

I dont know where is the problem...

**Comment by samwakel** [comment]
It’s here, delete the whole directory

VBoxManage: error: Machine settings file '/home/cuckoo/.vmcloak/vms/win7x64base/win7x64base.vbox' already exists

On 9 Jan 2021, at 8:04 am, Andrei Nedelcu <notifications@github.com> wrote:

VBoxManage: error: Machine settings file '/home/cuckoo/.vmcloak/vms/win7x64base/win7x64base.vbox' already exists

**Comment by andrie05** [comment]
Dont work... i delete IT and again this problem .

**Comment by andrie05** [comment]
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Failed to create medium
VBoxManage: error: Could not create the medium storage unit '/home/cuckoo/.vmcloak/image/win7x64base.vdi'.
VBoxManage: error: VDI: cannot create image '/home/cuckoo/.vmcloak/image/win7x64base.vdi' (VERR_ALREADY_EXISTS)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MediumWrap, interface IMedium
VBoxManage: error: Context: "RTEXITCODE handleCreateMedium(HandlerArg*)" at line 510 of file VBoxManageDisk.cpp
ERROR:vmcloak.vm:[-] Error running command: Command '['/usr/bin/VBoxManage', 'createhd', '--size', '262144', '--filename', '/home/cuckoo/.vmcloak/image/win7x64base.vdi']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/vmcloak", line 11, in <module>
    load_entry_point('VMCloak', 'console_scripts', 'vmcloak')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/cuckoo/.local/lib/python2.7/site-packages/vmcloak/main.py", line 265, in init
    m.create_hd(hdd_path, hddsize * 1024)
  File "/home/cuckoo/.local/lib/python2.7/site-packages/vmcloak/vm.py", line 100, in create_hd
    self._call("createhd", filename=hdd_path, size=fsize)
  File "/home/cuckoo/.local/lib/python2.7/site-packages/vmcloak/vm.py", line 41, in _call
    raise CommandError
vmcloak.exceptions.CommandError

**Comment by p-tekh** [comment]
Check your BIOS setttings. Maybe virtualization is not enabled. In case ot this, probably, you can't create x64 virtual machine.

**Comment by ezavalar** [comment]
Are you running this command on your virtualenv? I see your prompt doesn't have it, for example I created one named cuckoo-test so my prompt should be (cuckoo-test) ezavalar@ezavalar-VB:~$ you need to enter before you can install a virtual machine, once you create one use the command workon, in my case should be workon cuckoo-test and then try again, because I see the error could be the privilege of the command because you are not on virtualenv and you installed it on another folder, if that doesn't work you should try to change the machine's name for example: vmcloak init --win7x64 win7x64base_ --cpus 2 --ramsize 2048 -v -d

Notice if you do that you should continue the installation with the new name, I mean win7x64base_ instead win7x64base
I hope it works!

**Comment by pra7veen** [comment]
did it work
