### ISSUE TITLE
Snapshot issue

### ISSUE THREAD

**Issue by PizzaPablo666** [hatching/vmcloak#185]
$ vmcloak snapshot win7x64cuckoo cuckoo1 192.168.56.101                                              1 ⨯
/home/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
VBoxManage: error: Cannot change type for medium '/home/gt/.vmcloak/image/win7x64cuckoo.vdi': the media type 'MultiAttach' can only be used on media registered with a machine that was created with VirtualBox 4.0 or later
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "COMSETTER(Type)(enmMediumType)" at line 775 of file VBoxManageDisk.cpp
ERROR:vmcloak.vm:[-] Error running command: Command '['/usr/bin/VBoxManage', 'modifyhd', u'/home/gt/.vmcloak/image/win7x64cuckoo.vdi', '--type', 'multiattach']' returned non-zero exit status 1
Traceback (most recent call last):

my virtualbox version is 6.1

**Comment by ezavalar** [comment]
I know is closed but maybe this page could help, the solution is on point 6
[T0xicity Blog](https://t0xicity.com/blog/cuckoo_sandbox/)

**Comment by ammar0097** [comment]
vmcloak snapshot --count 4 win7x64cuckoo 192.168.56.101
VBoxManage: error: Machine settings file '/home/cuckoo/.vmcloak/vms/192.168.56.1011/192.168.56.1011.vbox' already exists
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "CreateMachine(bstrSettingsFile.raw(), bstrName.raw(), ComSafeArrayAsInParam(groups), bstrOsTypeId.raw(), createFlags.raw(), machine.asOutParam())" at line 276 of file VBoxManageMisc.cpp
ERROR:vmcloak.vm:[-] Error running command: Command '['/usr/bin/VBoxManage', 'createvm', '--register', '--name', '192.168.56.1011', '--basefolder', '/home/cuckoo/.vmcloak/vms']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/cuckoo/.virtualenvs/venv/bin/vmcloak", line 8, in <module>
    sys.exit(main())
  File "/home/cuckoo/.virtualenvs/venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/cuckoo/.virtualenvs/venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/cuckoo/.virtualenvs/venv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cuckoo/.virtualenvs/venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cuckoo/.virtualenvs/venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/cuckoo/.virtualenvs/venv/lib/python2.7/site-packages/vmcloak/main.py", line 584, in snapshot
    vrde, vrde_port, interactive
  File "/home/cuckoo/.virtualenvs/venv/lib/python2.7/site-packages/vmcloak/main.py", line 480, in do_snapshot
    m, h = initvm(image, name=vmname, multi=True, ramsize=ramsize, cpus=cpus)
  File "/home/cuckoo/.virtualenvs/venv/lib/python2.7/site-packages/vmcloak/main.py", line 57, in initvm
    m.create_vm()
  File "/home/cuckoo/.virtualenvs/venv/lib/python2.7/site-packages/vmcloak/vm.py", line 77, in create_vm
    basefolder=vms_path, register=True)
  File "/home/cuckoo/.virtualenvs/venv/lib/python2.7/site-packages/vmcloak/vm.py", line 41, in _call
    raise CommandError
vmcloak.exceptions.CommandError


anyone have the solution pls ? [T0xicity Blog](https://t0xicity.com/blog/cuckoo_sandbox/) not working ......
