### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by flngkttn** [hatching/vmcloak#191]
Hello there.

I'm unable to run vmcloak, because ssl certificate of https://cuckoo.sh has been expired tomorrow.
Could you somehow inform them about it or share some another way how to bypass ssl verification?

cuckoo@sandbox:~$ vmcloak init --vrde --resolution 800x600 --ramsize 4096 --win7x64 --product professional --cpus 4 win7x64 -v -d
/usr/local/lib/python2.7/dist-packages/pyOpenSSL-20.0.1-py2.7.egg/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
--2021-07-28 08:22:29--  https://cuckoo.sh/vmcloak/python-2.7.6.msi
**ERROR: cannot verify cuckoo.sh's certificate, issued by ‘CN=R3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.**
To connect to cuckoo.sh insecurely, use `--no-check-certificate'.
ERROR:vmcloak.abstract:The checksum of python27 doesn't match!
Traceback (most recent call last):
  File "/usr/local/bin/vmcloak", line 11, in <module>
    load_entry_point('VMCloak==0.4.3a2', 'console_scripts', 'vmcloak')()
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/VMCloak-0.4.3a2-py2.7.egg/vmcloak/main.py", line 214, in init
    d = Python27(i=Image(osversion=osversion))
  File "/usr/local/lib/python2.7/dist-packages/VMCloak-0.4.3a2-py2.7.egg/vmcloak/abstract.py", line 418, in __init__
    self.download()
  File "/usr/local/lib/python2.7/dist-packages/VMCloak-0.4.3a2-py2.7.egg/vmcloak/abstract.py", line 432, in download
    raise DependencyError
vmcloak.exceptions.DependencyError

**Comment by jbremer** [comment]
Thanks! This has now been resolved.
