### ISSUE TITLE
ValueError: need more than 1 value to unpack     while initialiing using vmcloak in it

### ISSUE THREAD

**Issue by Lathwal83** [hatching/vmcloak#210]
(cuckoo-test) cuckoo@cuckoo-HP-Pavilion-Gaming-Laptop-15-cx0xxx:~$ vmcloak init --verbose --win7x64 win7x64base --cpus 2 --ramsize 2048
/home/cuckoo/.virtualenvs/cuckoo-test/lib/python2.7/site-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
INFO:vmcloak:Starting the Virtual Machine u'win7x64base' to install Windows.
Traceback (most recent call last):
  File "/home/cuckoo/.virtualenvs/cuckoo-test/bin/vmcloak", line 8, in <module>
    sys.exit(main())
  File "/home/cuckoo/.virtualenvs/cuckoo-test/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/cuckoo/.virtualenvs/cuckoo-test/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/cuckoo/.virtualenvs/cuckoo-test/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cuckoo/.virtualenvs/cuckoo-test/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cuckoo/.virtualenvs/cuckoo-test/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/cuckoo/.virtualenvs/cuckoo-test/lib/python2.7/site-packages/vmcloak/main.py", line 275, in init
    m.wait_for_state(shutdown=True)
  File "/home/cuckoo/.virtualenvs/cuckoo-test/lib/python2.7/site-packages/vmcloak/vm.py", line 65, in wait_for_state
    status = self.vminfo("VMState")
  File "/home/cuckoo/.virtualenvs/cuckoo-test/lib/python2.7/site-packages/vmcloak/vm.py", line 49, in vminfo
    key, value = line.split("=", 1)
ValueError: need more than 1 value to unpack

sir its a little urgent . request if you can guide me through this at the on priority . please assit . Regards

**Comment by Dochous05** [comment]
Hi, i'm having the same error when trying to creat vms..did you find the solution?

**Comment by eingel86** [comment]
Hi, I have the same error too. Have you found a solution?
